name: Personnalize Action
description: Une Action Personnele Pour Le Test
author: Bouhroz

inputs:
  nom:
    description: username
    required: true

  langue:
    description: Language de salutation
    required: false
    default: fr

runs:
  using: node16
  main: index.js